

name: alvin
base: core18 # the base snap `s the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The main GUI for the Always Learning Voraciously International Navigator.
description: ???
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
   alvin:
      plugin: gradle
      source: https://github.com/williamjmcmillan/alvin.git
      source-type: git
      source-tag: master
      gradle-output-dir: build/libs
      build-environment:
      - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      - PATH: $JAVA_HOME/jre/bin:$PATH
      build-packages:
      - default-jdk
      - default-jre
      stage-packages:
      - default-jre
